// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApiKKMdaQghw83Pll0Zx9ta_cRrD4WpGY',
    appId: '1:163664774122:web:ebccb77ef647dae5ea2893',
    messagingSenderId: '163664774122',
    projectId: 'sharon-sir',
    authDomain: 'sharon-sir.firebaseapp.com',
    storageBucket: 'sharon-sir.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu3pC8CxYt6cUHlb4Kd9j9jm7pA50PBNc',
    appId: '1:163664774122:android:f15ebb90b43c9bd4ea2893',
    messagingSenderId: '163664774122',
    projectId: 'sharon-sir',
    storageBucket: 'sharon-sir.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxHV8yKStfVpu5bBEp-ZEjTTLDWUMNJ4E',
    appId: '1:163664774122:ios:e0c0c72e6ffb1a2cea2893',
    messagingSenderId: '163664774122',
    projectId: 'sharon-sir',
    storageBucket: 'sharon-sir.appspot.com',
    iosClientId: '163664774122-brireoi8g235mhupfhomq500lo57di7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharonSir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxHV8yKStfVpu5bBEp-ZEjTTLDWUMNJ4E',
    appId: '1:163664774122:ios:cc9656504f5143e5ea2893',
    messagingSenderId: '163664774122',
    projectId: 'sharon-sir',
    storageBucket: 'sharon-sir.appspot.com',
    iosClientId: '163664774122-mud8eknq9rqhm5pkf8q5895tnhul8222.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharonSir.RunnerTests',
  );
}
